# Generated by Django 4.2.6 on 2023-10-06 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_code', models.IntegerField(help_text='Major ID #')),
                ('degree_name', models.CharField(help_text='Degree name', max_length=200)),
                ('college_name', models.CharField(help_text='College name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='requiredCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(help_text='Subject name', max_length=200)),
                ('hours', models.IntegerField(help_text='hours required in subject')),
                ('classes_offered', models.CharField(help_text='classes offered', max_length=200)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.degree')),
            ],
        ),
        migrations.CreateModel(
            name='degreeSpecific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dSubject_name', models.CharField(help_text='Subject name', max_length=200)),
                ('dhours', models.IntegerField(help_text='hours required in subject')),
                ('dclasses_offered', models.CharField(help_text='classes offered', max_length=200)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree_checklist.degree')),
            ],
        ),
    ]
