# Generated by Django 4.2.5 on 2023-10-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree_checklist', '0002_rename_dhours_degreespecific_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreespecific',
            name='classCode',
            field=models.IntegerField(default=0, help_text='class ID #'),
            preserve_default=False,
        ),
    ]
